"""Seed corpus for the layer-2 theory memory (ChromaDB).

Each entry: `keywords` (English — this is what gets embedded/matched, because the
query string built in retrieve_memory_node uses the pipeline's English event
vocabulary) and `text` (Chinese — what the analyst actually receives and may quote).
Keep texts to one or two sentences: they are commentary material, not textbook pages.
"""

THEORY = [
    # --- 開局 openings ---
    {"id": "italian-two-knights",
     "keywords": "opening e4 e5 Nf3 Nc6 Bc4 italian game two knights defense bishop c4 targets f7",
     "text": "義大利開局體系中，白象上 c4 直指 f7——那是黑方王翼最脆弱的一格，開局階段只有國王保護它。"},
    {"id": "fried-liver",
     "keywords": "opening knight sacrifice capture f7 fried liver attack two knights Ng5 Nxf7 king attack fork",
     "text": "騎士在 f7 的犧牲是「炸雞肝攻擊」的招牌：用一隻馬換掉 f7 兵並引出黑王，後續靠將軍與雙重威脅把王困在中央。"},
    {"id": "ruy-lopez",
     "keywords": "opening e4 e5 Nf3 Nc6 Bb5 ruy lopez spanish bishop pins knight pressure",
     "text": "西班牙開局的 Bb5 對 c6 馬施壓，長期瞄準黑方 e5 兵的根基，是最古老也最深的開局體系之一。"},
    {"id": "sicilian",
     "keywords": "opening e4 c5 sicilian defense counterattack asymmetry queenside pawn majority",
     "text": "西西里防禦以 c5 換取不對稱局面：黑方放棄對稱的安全，換來後翼兵多數和反攻機會。"},
    {"id": "french",
     "keywords": "opening e4 e6 d5 french defense pawn chain light squared bishop blocked center",
     "text": "法蘭西防禦的代價寫在 c8 象上——e6 兵鏈把它關在家裡，黑方整盤棋常在想辦法讓這隻「壞象」出頭。"},
    {"id": "caro-kann",
     "keywords": "opening e4 c6 d5 caro kann solid structure endgame friendly",
     "text": "卡羅-卡恩防禦結構紮實、少弱點，黑方常樂於直接把局面導向對自己友善的殘局。"},
    {"id": "queens-gambit",
     "keywords": "opening d4 d5 c4 queens gambit declined center control pawn structure",
     "text": "后翼棄兵其實不是真棄：c4 兵用暫時的犧牲換中心控制，黑方若吃下 c4 往往守不住它。"},
    {"id": "reti-english",
     "keywords": "opening Nf3 c4 g3 reti english flank hypermodern fianchetto control center from distance",
     "text": "Réti 與英國式開局走「超現代」路線：不急著佔中心，先用側翼與斜線遙控中心，再伺機反撲。"},
    {"id": "london",
     "keywords": "opening d4 Bf4 london system solid setup same structure",
     "text": "倫敦系統以固定陣型著稱：白方幾乎不管對手怎麼下都擺出同一套結構，穩健但野心較小。"},

    # --- 戰術 tactics ---
    {"id": "fork",
     "keywords": "tactic fork knight double attack two pieces same time royal fork",
     "text": "捉雙（fork）是一子同時攻擊兩個目標，其中騎士捉雙最致命——它的走法無法被其他子力用同樣方式反制。"},
    {"id": "pin",
     "keywords": "tactic pin bishop rook queen piece cannot move behind more valuable",
     "text": "牽制（pin）讓一顆子動彈不得，因為它身後站著更值錢的目標；被牽制的子名義上在防守，實際上已經半殘。"},
    {"id": "skewer",
     "keywords": "tactic skewer attack valuable piece forced to move expose behind",
     "text": "串擊（skewer）是牽制的反面：先攻擊前面的大子，逼它讓開，吃掉躲在後面的目標。"},
    {"id": "discovered-attack",
     "keywords": "tactic discovered attack check piece moves away reveals attack behind",
     "text": "閃擊（discovered attack）一步製造兩個威脅：移開的子攻擊一處，讓出的火線攻擊另一處，對手往往只救得了一邊。"},
    {"id": "sac-f7-f2",
     "keywords": "tactic sacrifice capture f7 f2 weakest square king only defender expose king",
     "text": "f7（對白方是 f2）是全盤最弱的格子——開局只有國王守它。對這格的犧牲通常為了引王出洞，把王變成攻擊目標。"},
    {"id": "greek-gift",
     "keywords": "tactic sacrifice bishop h7 h2 greek gift castled king attack Ng5 Qh5",
     "text": "希臘禮物（Bxh7+）是對王車易位後國王的經典棄象：象換 h7 兵撕開王翼，馬跳 g5、后上 h5 的攻擊往往接踵而至。"},
    {"id": "back-rank",
     "keywords": "tactic back rank mate weakness rook queen king trapped behind pawns luft",
     "text": "底線弱點是被自己兵牆困住的國王：只要重子能殺進底線就是殺局，所以強手常提前走 h3 或 g3「開氣窗」。"},
    {"id": "deflection",
     "keywords": "tactic deflection overloaded defender remove the guard decoy",
     "text": "引離與超載：一顆子同時守兩件事就等於哪件都沒守穩，戰術打擊常從逼它二選一開始。"},
    {"id": "zwischenzug",
     "keywords": "tactic zwischenzug in between move intermediate check instead of recapture",
     "text": "中間步（zwischenzug）是拒絕「理所當然的回吃」：先插入一步將軍或更大的威脅，等對手應付完再回頭收帳。"},

    # --- 戰略 strategy ---
    {"id": "weak-pawns",
     "keywords": "strategy weak pawns isolated doubled backward pawn long term target blockade",
     "text": "孤兵、疊兵、落後兵是不會消失的長期目標；對付孤兵的標準方案是先封鎖（把馬架在它前面）再圍攻。"},
    {"id": "open-file",
     "keywords": "strategy open file rook seventh rank control heavy pieces invade",
     "text": "車要放在開放線上，而開放線的終點是第七橫排——車一旦殺進第七排，通常同時收割兵和限制對方國王。"},
    {"id": "bishop-pair",
     "keywords": "strategy bishop pair two bishops open position long diagonals advantage",
     "text": "雙象在開放局面是真實的長期優勢：兩隻象互補控制兩色格，局面越開放威力越大。"},
    {"id": "king-safety",
     "keywords": "strategy king safety castling exposed king center attack initiative",
     "text": "留在中央的國王是引擎評估暴跌的常見原因：中央線路一開，所有戰術都繞著這顆王轉。"},
    {"id": "initiative",
     "keywords": "strategy initiative tempo attack forcing moves pressure defender passive",
     "text": "先手（initiative）的價值在於逼對手一直回應你的威脅：防守方每步都被動，失誤率自然上升。"},
    {"id": "exchange-sac",
     "keywords": "strategy sacrifice exchange rook for minor piece compensation dark squares activity",
     "text": "棄換（車換輕子）換的不是子力是局面：常見補償是摧毀對方兵型、佔據無法驅逐的據點或掌控一色格。"},
    {"id": "prophylaxis",
     "keywords": "strategy prophylaxis prevent opponent plan improve worst piece quiet move",
     "text": "預防性著法（prophylaxis）先問「對手想幹嘛」再問「我想幹嘛」；頂尖棋手的安靜步多半是在拆對手還沒說出口的計畫。"},

    # --- 殘局 endgame ---
    {"id": "king-activity",
     "keywords": "endgame king activity centralize king strong piece walk forward",
     "text": "一進殘局規則就反轉：國王從被保護的對象變成戰力，王先走向中央的一方常常就是贏的一方。"},
    {"id": "passed-pawn",
     "keywords": "endgame passed pawn push promotion rook behind passed pawn blockade",
     "text": "通路兵是殘局的主角——「通路兵天生就想前進」；車的標準位置是站在通路兵後面，不論那是自己的還是對方的兵。"},
    {"id": "opposition",
     "keywords": "endgame king pawn opposition zugzwang key squares",
     "text": "王兵殘局的勝負常繫於「對王」（opposition）：兩王對峙時，輪到誰走誰吃虧——這是最純粹的 zugzwang。"},
    {"id": "mate-technique",
     "keywords": "endgame checkmate mate sequence technique convert winning advantage no stalemate",
     "text": "殺王階段的紀律是：縮小王的活動空間、提防逼和陷阱、不給任何反擊機會——贏定的棋最怕的只有大意。"},
]
